name: notification-service

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    init: true
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro

  worker:
    build:
      dockerfile: Dockerfile
      context: .
    init: true
    env_file:
      - .env
    environment:
      RABBITMQ_HOST: rabbitmq
      PYTHONPATH: /app/src
    depends_on:
      - rabbitmq
    volumes:
      - ./src:/app/src:ro
    command:
      [
        "celery",
        "-A",
        "notification_service.messaging.celery_app:celery_app",
        "worker",
        "--loglevel=INFO",
        "--queues=notifications",
      ]

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: