"""add locked_until to outbox event

Revision ID: 48be7c5f8b96
Revises: f8c79ef26e55
Create Date: 2026-10-04 21:01:52.159759

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '48be7c5f8b96'
down_revision: str | Sequence[str] | None = 'f8c79ef26e55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'locked_until')
    # ### end Alembic commands ###
